### ISSUE TITLE
Improvement of the installation doc

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [tailwindlabs/tailwindcss.com#839] opened 2021-05-10 00:21 UTC
I'm using Tailwind on Windows with create react app. I clearly followed the document and it works. However, I found that the auto reload doesn't work anymore. After some investigating, I found that I need to create a file `.env` with the content `FAST_REFRESH=false` to make it work. I hope you can add this step to the document. I only tested on Windows, though.

**Comment by adamwathan** [comment] 2021-05-22 19:58
Hey thanks for raising this! This is the first I've heard of it and I don't have an easy way to test on Windows myself so I can't reproduce and verify the fix, so I don't want to add to the docs prematurely in case the problem/solution isn't exactly what you've described. I'm going to close this without making any changes for now but if we start to hear about this more then we can figure out a way to look into it deeper. Thanks again.

**Closed by adamwathan** 2021-05-22 19:58 UTC
