### ISSUE TITLE
Dark mode toggle!

### ISSUE THREAD

**Issue by ankityadavhere** [tailwindlabs/tailwindcss.com#928] opened 2021-08-29 08:14 UTC
**It hurts** while taking references from docs when you're writing code in dark!

Also, third-party dark mode extensions don't work properly.

**Comment by AtulPatil-me** [comment] 2021-08-29 08:15
+1

**Comment by tomprats** [comment] 2021-09-09 16:09
Took a quick look into this to see if I could start a PR.

For the most part it looks like we'd need to add `dark:` version pretty much wherever there is a `bg-` or `text-` class. Does that seem right?

Any advice or color choices before I attempt to give it a go?

**Comment by ankityadavhere** [comment] 2021-09-09 23:12
> Took a quick look into this to see if I could start a PR.
> 
> For the most part it looks like we'd need to add `dark:` version pretty much wherever there is a `bg-` or `text-` class. Then also enabling dark mode. Does that seem right?
> 
> Any advice or color choices before I attempt to give it a go?


@tomprats Anything will look good except these high contrast combinations (#000 & #FFF)

**Comment by ankityadavhere** [comment] 2021-09-09 23:12
> Took a quick look into this to see if I could start a PR.
> 
> For the most part it looks like we'd need to add `dark:` version pretty much wherever there is a `bg-` or `text-` class. Then also enabling dark mode. Does that seem right?
> 
> Any advice or color choices before I attempt to give it a go?


@tomprats Anything will look good except these high contrast combinations (#000 & #FFF)

**Comment by adamwathan** [comment] 2021-09-10 19:05
Thanks for the suggestion! This is something we'd like to do and have started exploring, hoping we can include it with the redesign we are currently working on but don't want to make any promises because it's a lot of work 🥵

Please **don't** open a pull request for something as big as this because it will almost certainly get closed — there's just way too much that go into making this really good and we'd have a lot of strong opinions on it and doing it back and forth over GitHub just isn't something we'll have time for. I would feel like a total jerk closing a PR someone spent hours and hours on.

Going to close as a not a bug/issue per se, but feedback definitely noted and hopefully something we can do.

**Closed by adamwathan** 2021-09-10 19:05 UTC

**Comment by ankityadavhere** [comment] 2021-09-10 22:48
Thanks for your response Adam! looking forward to the new redesign! 👀

**Comment by obiknows** [comment] 2021-12-09 23:30
please...the dark mode so necessary

**Comment by reinink** [comment] 2021-12-20 15:11
Hey ya'll, the docs website [is now available](https://twitter.com/tailwindcss/status/1472945416035520519) in dark mode 🙌

[![image](https://user-images.githubusercontent.com/882133/146788599-94a8a7d8-6428-46c3-a097-caa942a80c87.png)](https://tailwindcss.com/)
