### ISSUE TITLE
Quick Search doesn't work

### ISSUE THREAD

**Issue by Ne3mah** [tailwindlabs/tailwindcss.com#1897] opened 2024-11-03 16:41 UTC
![image](https://github.com/user-attachments/assets/9b44b076-0e36-4a2f-a390-fa8a3276fc32)

**Comment by adamwathan** [comment] 2024-11-04 20:22
Hey! I can't reproduce this:

<img width="1475" alt="image" src="https://github.com/user-attachments/assets/038abeb0-ce17-49ee-9459-b799a4d53c2f">

Going to chalk it up to a temporary issue with Algolia or something and close this one. If you find a way to reliably reproduce it though please open a new issue and we can look into it.

**Closed by adamwathan** 2024-11-04 20:22 UTC
