### ISSUE TITLE
`hyphens-none` example not displaying correctly 

### ISSUE THREAD

**Issue by joseph-coyne** [tailwindlabs/tailwindcss.com#1705] opened 2023-10-18 19:42 UTC
[Documentation example ](https://tailwindcss.com/docs/hyphens)for `hyphens-none` seems to be broken.

Using Chrome Version 118.0.5993.88 (Official Build) (arm64)

<img width="684" alt="Screenshot 2023-10-18 at 3 38 26 PM" src="https://github.com/tailwindlabs/tailwindcss.com/assets/39542045/d912a5e3-de28-4bd6-a2ba-7a622cb6c78f">

**Comment by thecrypticace** [comment] 2023-10-19 17:20
Looks like a bug introduced in Chrome 116 and still present in Chrome Canary. The bug doesn't happen in simple cases so I'll see if I can figure out a workaround or a reproduction of some kind to file a bug report.

**Comment by thecrypticace** [comment] 2023-10-19 17:43
Reproduction: https://play.tailwindcss.com/3jNc50PANE

It seems like Chrome is hyphenating when using soft hyphens when it should not in this case.

**Comment by thecrypticace** [comment] 2023-10-30 15:28
I opened a bug for this: https://bugs.chromium.org/p/chromium/issues/detail?id=1497495

**Comment by thecrypticace** [comment] 2023-11-07 16:23
I'm gonna close this since this is being tracked in the Chromium bug. Hopefully they'll get it patched and fixed soon.

**Closed by thecrypticace** 2023-11-07 16:23 UTC
