### ISSUE TITLE
The following features are expected to be added to the document

### ISSUE THREAD

**Issue by wsdo** [tailwindlabs/tailwindcss.com#1158] opened 2022-01-24 10:46 UTC
![image](https://user-images.githubusercontent.com/9738969/150768948-d7573285-a701-4987-bed3-cf097e46b7a2.png)

add copy button

**Comment by adamwathan** [comment] 2022-01-24 14:16
Thanks for the feedback, will take it into consideration. Closing since not a bug but again do appreciate the suggestion.

**Closed by adamwathan** 2022-01-24 14:16 UTC
