### ISSUE TITLE
searching is slow

### ISSUE THREAD

**Issue by not-rusty** [tailwindlabs/tailwindcss.com#1447] opened 2022-11-28 10:21 UTC
I use tailwindcss everyday. And everyday, I look up for the equivalent css property. Typing it out to the search box was once a bit fast (not excellent, but okeish), but its getting sluggish. While I'm typing the property the text input lags, which is really uncomfortable.

**Comment by reinink** [comment] 2022-11-28 12:15
Hey! Can you share what browser and operating system you're using? I just gave this a try in Chrome, Firefox, and Safari, and I'm not able to reproduce it. Could you maybe share a similar video as well?

https://user-images.githubusercontent.com/882133/204275307-f060c77c-26d7-47e3-844b-b41c9030212a.mov

**Comment by not-rusty** [comment] 2022-11-28 19:01
I'm on Linux, Ubuntu 20.04

Chrome: Version 106.0.5249.103 (Official Build) (64-bit)

It is strange, on Firefox this doesn't happen that much, the search is like 50% faster. The only way I can really prove it is by holding some character until it repeats.
@reinink try holding a key on the search box on both firefox and chrome. On my machine in firefox feels faster than on chrome.

Here's my proof:

On chrome:

https://user-images.githubusercontent.com/16207732/204358432-0e9f20c8-4f80-4a9b-8346-53c9b930c853.mov

On firefox:

https://user-images.githubusercontent.com/16207732/204358466-e12708b3-ca63-4f91-a923-158d068a8f73.mov

From the videos it might not be noticeable, but it feels like on chrome after typing a character the text input lags for 60ms or something, enough to be annoying.

Writing the response I saw that on firefox the search box works really smooth. It also lags on the first characters written, but much less than chrome.

**Comment by reinink** [comment] 2022-11-30 18:56
Hey thanks for sharing this extra info — definitely odd that this is happening for you. I wonder if this is related to Linux somehow.

Since I'm unable to reproduce this issue it makes it very hard to fix, plus we're using the `@docsearch/react` library for this search feature, so it's entirely possible the issue actually lies there. So given that, and also the fact that this doesn't seem to be affecting other users, I think I'm going to close this issue for now.

That said, if you're feeling ambitious, feel free to try and dig into this yourself, especially since you're able to reproduce the issue on your end. No pressure obviously 😅

Thanks either way for reporting — sorry I cannot be more helpful than that!

**Closed by reinink** 2022-11-30 18:56 UTC
