### ISSUE TITLE
The Details disclosure element is very slow on opening/closing

### ISSUE THREAD

**Issue by AlexWebLab** [tailwindlabs/tailwindcss.com#1051] opened 2021-12-15 08:33 UTC
The Details disclosure element with Summary "How does this compare to traditional CSS?" is very slow on opening/closing at this page:
[https://tailwindcss.com/docs/hover-focus-and-other-states](https://tailwindcss.com/docs/hover-focus-and-other-states)

but it's very snappy here:
[https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/hover-focus-and-other-states.mdx](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/hover-focus-and-other-states.mdx)

I cannot figure how to debug and why it's happening 🤷🏻

**Comment by LoganDark** [comment] 2021-12-28 12:07
![image](https://user-images.githubusercontent.com/4723091/147564675-e182e698-abce-43e1-bb9a-8bcb4d5b80f7.png)

Layout shift, it happens because the disclosure element contains something that the browser really, really doesn't like.

I sometimes run into issues like these where the browser takes forever to work through a layout shift like this. They're not solvable with the profiling tools we have today

**Comment by AlexWebLab** [comment] 2021-12-29 03:14
@LoganDark 
Thank you for the explanation. From where that image is cropped? Can you please tell me how to see/generate that? I really love to inspect at this level of detail. Thanks a lot.

**Comment by reinink** [comment] 2022-01-07 12:41
Hey! Thanks for reporting this. This is truly a weird issue — something is obviously happening in React land to cause this. I've spent some time digging into it, trying a bunch of different things, and nothing helped. So while I agree this is annoying/weird, I am going to close this issue, just because there isn't a clear obvious fix, and also because it still technically works. If anyone here wants to do more digging into this and figure out the cause, I'd be grateful! 🙏

**Closed by reinink** 2022-01-07 12:41 UTC

**Comment by LoganDark** [comment] 2022-01-07 15:00
> @LoganDark Thank you for the explanation. From where that image is cropped? Can you please tell me how to see/generate that? I really love to inspect at this level of detail. Thanks a lot.

Sorry for the late response. It's the Performance tab of the Chrome DevTools. That's the performance profiler
