### ISSUE TITLE
Search for "button" in docs yields one unexpected answer

### ISSUE THREAD

**Issue by christoferd** [tailwindlabs/tailwindcss.com#960] opened 2021-10-04 21:26 UTC
Issue: 
Search for "button" in docs yields one unexpected answer.
= Preflight - Buttons have a default outline

Expected:
To see some documentation on "button" class, or something to do with CSS and buttons :-/

Reproduce:
1. Go to [tailwind docs](https://tailwindcss.com/docs)
2. Search for "button" using the search bar at the top (powered by algolia)
 
Suggested Improvement:
Maybe the ["Buttons" components page](https://v1.tailwindcss.com/components/buttons) should appear in the results.

**Comment by adamwathan** [comment] 2021-10-04 23:52
Hey! Since Tailwind doesn't actually include any components like buttons/card/form controls/etc., the search results are actually accurate — we don't have any documentation on buttons since building a button is up to you.

The buttons page you linked is from the old v1 documentation but we ended up removing it when we redesigned the site.

Definitely could be value in adding some information on how to build your own buttons but going to close this as at least not a bug, and instead just something to consider the next time I do any major documentation revamping. Thanks!

**Closed by adamwathan** 2021-10-04 23:52 UTC
